CREATE TABLE TODO (
TD_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
TD_NAME VARCHAR(255) NOT NULL,
TD_DESCIPTION VARCHAR(500),
TD_STARTDATE TIMESTAMP NULL,
TD_ENDDATE TIMESTAMP NULL,
TD_TYPE INT NOT NULL
);

commit;

INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Staubsaugen', 'Wohnzimmer dreckick, bitte putzen!', current_timestamp, current_timestamp, 1);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Einkaufen', 'Hunger, Bitte Einkaufen!!', null , null , 2);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Fenster putzen', null,null,null, 1);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Bier Trinken', null,null,null, 1);