DROP TABLE IF EXISTS TODO;
DROP TABLE IF EXISTS TODO_TYPE;
commit;

CREATE TABLE TODO_TYPE (
TDT_ID INT(6) PRIMARY KEY,
TDT_NAME VARCHAR(50) NOT NULL
);
commit;

CREATE TABLE TODO (
TD_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
TD_NAME VARCHAR(255) NOT NULL,
TD_DESCRIPTION VARCHAR(500) ,
TD_STARTDATE TIMESTAMP NULL,
TD_ENDDATE TIMESTAMP NULL,
TD_TYPE INT(6) NOT NULL,
FOREIGN KEY (TD_TYPE) REFERENCES TODO_TYPE(TDT_ID)
);
commit;

INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Staubsaugen', 'Wohnzimmer dreckick, bitte putzen!', current_timestamp, current_timestamp, 1);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Einkaufen', 'Hunger, Bitte Einkaufen!!', null , null , 2);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Fenster putzen', null,null,null, 1);
INSERT INTO TODO (TD_NAME,TD_DESCRIPTION,TD_STARTDATE,TD_ENDDATE,TD_TYPE) VALUES ('Bier Trinken', null,null,null, 1);